apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  labels:
    app: pipelines-vote-ui
  name: pipelines-vote-ui
  namespace: app-vote-dev
spec:
  replicas: 4
  revisionHistoryLimit: 5
  strategy:
    canary:
      steps:
        - setWeight: 20  # Envia 20% do tráfego para a nova versão
        - pause: {}      # Pausa indefinidamente até aprovação manual!
        - setWeight: 50  # Envia 50% do tráfego
        - pause: { duration: 2m } # Pausa automática de 2 minutos antes de finalizar (100%)
  selector:
    matchLabels:
      app: pipelines-vote-ui
  template:
    metadata:
      labels:
        app: pipelines-vote-ui
    spec:
      containers:
        - name: pipelines-vote-ui
          image: image-registry.openshift-image-registry.svc:5000/pipelines-tutorial/pipelines-vote-ui:30723934e09ed5e314c5ffaaa664e441cb511a32
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 9090
              protocol: TCP
          env:
            - name: VOTING_API_SERVICE_HOST
              value: pipelines-vote-api
            - name: VOTING_API_SERVICE_PORT
              value: "9000"