apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pipelines-vote-api
  name: pipelines-vote-api
  namespace: app-vote-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pipelines-vote-api
  template:
    metadata:
      labels:
        app: pipelines-vote-api
    spec:
      containers:
        - image: image-registry.openshift-image-registry.svc:5000/pipelines-tutorial/pipelines-vote-api:22da5a07fa5ac16cd454c78600561fbcb9c6559f
          imagePullPolicy: Always
          name: pipelines-vote-api
          ports:
            - containerPort: 9000
              protocol: TCP
